# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1042fa77aecd237cd7545b905f4ad357ded866671d6376cbb30f64f886456fced9e42946bd76c0c22260c8b43df35e1915414dddc25cd386fbdfa6eae373a359

test:
  secret_key_base: 30becad57732b0f5b3b4ee511b160d3320b48123392a7d47da8d889646dc99650c38e4fa3ed76412c2da631d7bd84b41296ab93cb3f3e04c9c98b8f379d59b4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
